use std::cmp::Ordering;
use std::hash::{Hash, Hasher};
use std::ops::Range;
use std::path::{Path, PathBuf};

use kode_acquisition::Language;

use crate::extraction::diagnostic::ExtractionDiagnostic;
use kode_common::hash::Fnv1aHasher;

/// Stable, deterministic identifier for an extracted entity.
///
/// Generated by hashing (language, kind, file path, name, byte offset),
/// guaranteeing uniqueness and reproducibility regardless of traversal order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct EntityId(u64);

impl EntityId {
    pub fn from_location(
        language: &Language,
        kind: &str,
        path: &Path,
        name: &str,
        byte_offset: usize,
    ) -> Self {
        let mut hasher = Fnv1aHasher::new();
        language.hash(&mut hasher);
        kind.hash(&mut hasher);
        path.hash(&mut hasher);
        name.hash(&mut hasher);
        byte_offset.hash(&mut hasher);
        Self(hasher.finish())
    }

    pub fn as_u64(&self) -> u64 {
        self.0
    }

    /// Create an `EntityId` from a raw u64 value.
    ///
    /// # Safety
    ///
    /// The caller must ensure the value was produced by
    /// [`EntityId::from_location`] or [`EntityId::as_u64`].
    /// This constructor does not recompute the hash.
    pub fn from_u64(value: u64) -> Self {
        Self(value)
    }
}

impl Ord for EntityId {
    fn cmp(&self, other: &Self) -> Ordering {
        self.0.cmp(&other.0)
    }
}

impl PartialOrd for EntityId {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl std::fmt::Display for EntityId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:016x}", self.0)
    }
}

/// Source location evidence for an extracted entity.
///
/// Every entity must have evidence tracing it back to the source code.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Evidence {
    source_file: PathBuf,
    node_kind: String,
    byte_range: Range<usize>,
    start_line: usize,
    start_column: usize,
    end_line: usize,
    end_column: usize,
    language: Language,
}

impl Evidence {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        source_file: PathBuf,
        node_kind: impl Into<String>,
        byte_range: Range<usize>,
        start_line: usize,
        start_column: usize,
        end_line: usize,
        end_column: usize,
        language: Language,
    ) -> Self {
        Self {
            source_file,
            node_kind: node_kind.into(),
            byte_range,
            start_line,
            start_column,
            end_line,
            end_column,
            language,
        }
    }

    pub fn source_file(&self) -> &Path {
        &self.source_file
    }

    pub fn node_kind(&self) -> &str {
        &self.node_kind
    }

    pub fn byte_range(&self) -> &Range<usize> {
        &self.byte_range
    }

    pub fn start_line(&self) -> usize {
        self.start_line
    }

    pub fn start_column(&self) -> usize {
        self.start_column
    }

    pub fn end_line(&self) -> usize {
        self.end_line
    }

    pub fn end_column(&self) -> usize {
        self.end_column
    }

    pub fn language(&self) -> &Language {
        &self.language
    }
}

/// Visibility level for Rust items.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Visibility {
    Public,
    Crate,
    Super,
    Restricted(String),
    Private,
}

impl std::fmt::Display for Visibility {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Visibility::Public => write!(f, "public"),
            Visibility::Crate => write!(f, "crate"),
            Visibility::Super => write!(f, "super"),
            Visibility::Private => write!(f, "private"),
            Visibility::Restricted(s) => write!(f, "restricted({s})"),
        }
    }
}

impl std::str::FromStr for Visibility {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "public" => Ok(Visibility::Public),
            "crate" => Ok(Visibility::Crate),
            "super" => Ok(Visibility::Super),
            "private" => Ok(Visibility::Private),
            r if r.starts_with("restricted(") && r.ends_with(')') => {
                Ok(Visibility::Restricted(r[11..r.len() - 1].to_string()))
            }
            other => Err(format!("unknown visibility: {other}")),
        }
    }
}

// ---------------------------------------------------------------------------
// Entity types
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModuleFact {
    id: EntityId,
    name: String,
    visibility: Visibility,
    evidence: Evidence,
}

impl ModuleFact {
    pub fn new(
        id: EntityId,
        name: impl Into<String>,
        visibility: Visibility,
        evidence: Evidence,
    ) -> Self {
        Self {
            id,
            name: name.into(),
            visibility,
            evidence,
        }
    }

    pub fn id(&self) -> &EntityId {
        &self.id
    }
    pub fn name(&self) -> &str {
        &self.name
    }
    pub fn visibility(&self) -> &Visibility {
        &self.visibility
    }
    pub fn evidence(&self) -> &Evidence {
        &self.evidence
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StructField {
    id: EntityId,
    name: String,
    field_type: Option<String>,
    visibility: Visibility,
    evidence: Evidence,
}

impl StructField {
    pub fn new(
        id: EntityId,
        name: impl Into<String>,
        field_type: Option<String>,
        visibility: Visibility,
        evidence: Evidence,
    ) -> Self {
        Self {
            id,
            name: name.into(),
            field_type,
            visibility,
            evidence,
        }
    }

    pub fn id(&self) -> &EntityId {
        &self.id
    }
    pub fn name(&self) -> &str {
        &self.name
    }
    pub fn field_type(&self) -> Option<&str> {
        self.field_type.as_deref()
    }
    pub fn visibility(&self) -> &Visibility {
        &self.visibility
    }
    pub fn evidence(&self) -> &Evidence {
        &self.evidence
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StructFact {
    id: EntityId,
    name: String,
    fields: Vec<StructField>,
    visibility: Visibility,
    generics: Vec<String>,
    evidence: Evidence,
}

impl StructFact {
    pub fn new(
        id: EntityId,
        name: impl Into<String>,
        fields: Vec<StructField>,
        visibility: Visibility,
        generics: Vec<String>,
        evidence: Evidence,
    ) -> Self {
        Self {
            id,
            name: name.into(),
            fields,
            visibility,
            generics,
            evidence,
        }
    }

    pub fn id(&self) -> &EntityId {
        &self.id
    }
    pub fn name(&self) -> &str {
        &self.name
    }
    pub fn fields(&self) -> &[StructField] {
        &self.fields
    }
    pub fn visibility(&self) -> &Visibility {
        &self.visibility
    }
    pub fn generics(&self) -> &[String] {
        &self.generics
    }
    pub fn evidence(&self) -> &Evidence {
        &self.evidence
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EnumVariant {
    id: EntityId,
    name: String,
    discriminant: Option<String>,
    evidence: Evidence,
}

impl EnumVariant {
    pub fn new(
        id: EntityId,
        name: impl Into<String>,
        discriminant: Option<String>,
        evidence: Evidence,
    ) -> Self {
        Self {
            id,
            name: name.into(),
            discriminant,
            evidence,
        }
    }

    pub fn id(&self) -> &EntityId {
        &self.id
    }
    pub fn name(&self) -> &str {
        &self.name
    }
    pub fn discriminant(&self) -> Option<&str> {
        self.discriminant.as_deref()
    }
    pub fn evidence(&self) -> &Evidence {
        &self.evidence
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EnumFact {
    id: EntityId,
    name: String,
    variants: Vec<EnumVariant>,
    visibility: Visibility,
    evidence: Evidence,
}

impl EnumFact {
    pub fn new(
        id: EntityId,
        name: impl Into<String>,
        variants: Vec<EnumVariant>,
        visibility: Visibility,
        evidence: Evidence,
    ) -> Self {
        Self {
            id,
            name: name.into(),
            variants,
            visibility,
            evidence,
        }
    }

    pub fn id(&self) -> &EntityId {
        &self.id
    }
    pub fn name(&self) -> &str {
        &self.name
    }
    pub fn variants(&self) -> &[EnumVariant] {
        &self.variants
    }
    pub fn visibility(&self) -> &Visibility {
        &self.visibility
    }
    pub fn evidence(&self) -> &Evidence {
        &self.evidence
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FunctionFact {
    id: EntityId,
    name: String,
    visibility: Visibility,
    signature: Option<String>,
    generics: Vec<String>,
    is_async: bool,
    is_const: bool,
    is_unsafe: bool,
    documentation: Option<String>,
    containing_trait: Option<EntityId>,
    containing_impl: Option<EntityId>,
    evidence: Evidence,
}

impl FunctionFact {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        id: EntityId,
        name: impl Into<String>,
        visibility: Visibility,
        signature: Option<String>,
        generics: Vec<String>,
        is_async: bool,
        is_const: bool,
        is_unsafe: bool,
        documentation: Option<String>,
        containing_trait: Option<EntityId>,
        containing_impl: Option<EntityId>,
        evidence: Evidence,
    ) -> Self {
        Self {
            id,
            name: name.into(),
            visibility,
            signature,
            generics,
            is_async,
            is_const,
            is_unsafe,
            documentation,
            containing_trait,
            containing_impl,
            evidence,
        }
    }

    pub fn id(&self) -> &EntityId {
        &self.id
    }
    pub fn name(&self) -> &str {
        &self.name
    }
    pub fn visibility(&self) -> &Visibility {
        &self.visibility
    }
    pub fn signature(&self) -> Option<&str> {
        self.signature.as_deref()
    }
    pub fn generics(&self) -> &[String] {
        &self.generics
    }
    pub fn is_async(&self) -> bool {
        self.is_async
    }
    pub fn is_const(&self) -> bool {
        self.is_const
    }
    pub fn is_unsafe(&self) -> bool {
        self.is_unsafe
    }
    pub fn documentation(&self) -> Option<&str> {
        self.documentation.as_deref()
    }
    pub fn containing_trait(&self) -> Option<&EntityId> {
        self.containing_trait.as_ref()
    }
    pub fn containing_impl(&self) -> Option<&EntityId> {
        self.containing_impl.as_ref()
    }
    pub fn evidence(&self) -> &Evidence {
        &self.evidence
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TraitFact {
    id: EntityId,
    name: String,
    visibility: Visibility,
    methods: Vec<EntityId>,
    associated_types: Vec<EntityId>,
    associated_constants: Vec<EntityId>,
    evidence: Evidence,
}

impl TraitFact {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        id: EntityId,
        name: impl Into<String>,
        visibility: Visibility,
        methods: Vec<EntityId>,
        associated_types: Vec<EntityId>,
        associated_constants: Vec<EntityId>,
        evidence: Evidence,
    ) -> Self {
        Self {
            id,
            name: name.into(),
            visibility,
            methods,
            associated_types,
            associated_constants,
            evidence,
        }
    }

    pub fn id(&self) -> &EntityId {
        &self.id
    }
    pub fn name(&self) -> &str {
        &self.name
    }
    pub fn visibility(&self) -> &Visibility {
        &self.visibility
    }
    pub fn methods(&self) -> &[EntityId] {
        &self.methods
    }
    pub fn associated_types(&self) -> &[EntityId] {
        &self.associated_types
    }
    pub fn associated_constants(&self) -> &[EntityId] {
        &self.associated_constants
    }
    pub fn evidence(&self) -> &Evidence {
        &self.evidence
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImplBlockFact {
    id: EntityId,
    target_type: String,
    implemented_trait: Option<String>,
    methods: Vec<EntityId>,
    evidence: Evidence,
}

impl ImplBlockFact {
    pub fn new(
        id: EntityId,
        target_type: impl Into<String>,
        implemented_trait: Option<String>,
        methods: Vec<EntityId>,
        evidence: Evidence,
    ) -> Self {
        Self {
            id,
            target_type: target_type.into(),
            implemented_trait,
            methods,
            evidence,
        }
    }

    pub fn id(&self) -> &EntityId {
        &self.id
    }
    pub fn target_type(&self) -> &str {
        &self.target_type
    }
    pub fn implemented_trait(&self) -> Option<&str> {
        self.implemented_trait.as_deref()
    }
    pub fn methods(&self) -> &[EntityId] {
        &self.methods
    }
    pub fn evidence(&self) -> &Evidence {
        &self.evidence
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TypeAliasFact {
    id: EntityId,
    name: String,
    aliased_type: Option<String>,
    evidence: Evidence,
}

impl TypeAliasFact {
    pub fn new(
        id: EntityId,
        name: impl Into<String>,
        aliased_type: Option<String>,
        evidence: Evidence,
    ) -> Self {
        Self {
            id,
            name: name.into(),
            aliased_type,
            evidence,
        }
    }

    pub fn id(&self) -> &EntityId {
        &self.id
    }
    pub fn name(&self) -> &str {
        &self.name
    }
    pub fn aliased_type(&self) -> Option<&str> {
        self.aliased_type.as_deref()
    }
    pub fn evidence(&self) -> &Evidence {
        &self.evidence
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConstantFact {
    id: EntityId,
    name: String,
    const_type: Option<String>,
    value: Option<String>,
    evidence: Evidence,
}

impl ConstantFact {
    pub fn new(
        id: EntityId,
        name: impl Into<String>,
        const_type: Option<String>,
        value: Option<String>,
        evidence: Evidence,
    ) -> Self {
        Self {
            id,
            name: name.into(),
            const_type,
            value,
            evidence,
        }
    }

    pub fn id(&self) -> &EntityId {
        &self.id
    }
    pub fn name(&self) -> &str {
        &self.name
    }
    pub fn const_type(&self) -> Option<&str> {
        self.const_type.as_deref()
    }
    pub fn value(&self) -> Option<&str> {
        self.value.as_deref()
    }
    pub fn evidence(&self) -> &Evidence {
        &self.evidence
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StaticFact {
    id: EntityId,
    name: String,
    static_type: Option<String>,
    is_mutable: bool,
    evidence: Evidence,
}

impl StaticFact {
    pub fn new(
        id: EntityId,
        name: impl Into<String>,
        static_type: Option<String>,
        is_mutable: bool,
        evidence: Evidence,
    ) -> Self {
        Self {
            id,
            name: name.into(),
            static_type,
            is_mutable,
            evidence,
        }
    }

    pub fn id(&self) -> &EntityId {
        &self.id
    }
    pub fn name(&self) -> &str {
        &self.name
    }
    pub fn static_type(&self) -> Option<&str> {
        self.static_type.as_deref()
    }
    pub fn is_mutable(&self) -> bool {
        self.is_mutable
    }
    pub fn evidence(&self) -> &Evidence {
        &self.evidence
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImportFact {
    id: EntityId,
    path: String,
    alias: Option<String>,
    is_glob: bool,
    evidence: Evidence,
}

impl ImportFact {
    pub fn new(
        id: EntityId,
        path: impl Into<String>,
        alias: Option<String>,
        is_glob: bool,
        evidence: Evidence,
    ) -> Self {
        Self {
            id,
            path: path.into(),
            alias,
            is_glob,
            evidence,
        }
    }

    pub fn id(&self) -> &EntityId {
        &self.id
    }
    pub fn path(&self) -> &str {
        &self.path
    }
    pub fn alias(&self) -> Option<&str> {
        self.alias.as_deref()
    }
    pub fn is_glob(&self) -> bool {
        self.is_glob
    }
    pub fn evidence(&self) -> &Evidence {
        &self.evidence
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExportFact {
    id: EntityId,
    path: String,
    alias: Option<String>,
    is_reexport: bool,
    evidence: Evidence,
}

impl ExportFact {
    pub fn new(
        id: EntityId,
        path: impl Into<String>,
        alias: Option<String>,
        is_reexport: bool,
        evidence: Evidence,
    ) -> Self {
        Self {
            id,
            path: path.into(),
            alias,
            is_reexport,
            evidence,
        }
    }

    pub fn id(&self) -> &EntityId {
        &self.id
    }
    pub fn path(&self) -> &str {
        &self.path
    }
    pub fn alias(&self) -> Option<&str> {
        self.alias.as_deref()
    }
    pub fn is_reexport(&self) -> bool {
        self.is_reexport
    }
    pub fn evidence(&self) -> &Evidence {
        &self.evidence
    }
}

/// Discriminated entity type wrapping all fact variants.
#[derive(Debug, Clone)]
pub enum Entity {
    Module(ModuleFact),
    Function(FunctionFact),
    Struct(StructFact),
    Enum(EnumFact),
    Trait(TraitFact),
    ImplBlock(ImplBlockFact),
    TypeAlias(TypeAliasFact),
    Constant(ConstantFact),
    Static(StaticFact),
    Import(ImportFact),
    Export(ExportFact),
}

// ---------------------------------------------------------------------------
// RepositoryFacts
// ---------------------------------------------------------------------------

/// Immutable, complete extracted semantic model for a repository.
///
/// Owns all extracted entities with deterministic ordering and
/// evidence attached to every entity.
#[derive(Debug, Clone)]
pub struct RepositoryFacts {
    modules: Vec<ModuleFact>,
    functions: Vec<FunctionFact>,
    structs: Vec<StructFact>,
    enums: Vec<EnumFact>,
    traits: Vec<TraitFact>,
    impl_blocks: Vec<ImplBlockFact>,
    type_aliases: Vec<TypeAliasFact>,
    constants: Vec<ConstantFact>,
    statics: Vec<StaticFact>,
    imports: Vec<ImportFact>,
    exports: Vec<ExportFact>,
    diagnostics: Vec<ExtractionDiagnostic>,
}

impl RepositoryFacts {
    /// Construct from a flat vector of entities and diagnostics.
    ///
    /// Entities are partitioned by type and sorted by [`EntityId`]
    /// for deterministic ordering independent of traversal order.
    pub fn from_entities(entities: Vec<Entity>, diagnostics: Vec<ExtractionDiagnostic>) -> Self {
        let mut modules = Vec::new();
        let mut functions = Vec::new();
        let mut structs = Vec::new();
        let mut enums = Vec::new();
        let mut traits = Vec::new();
        let mut impl_blocks = Vec::new();
        let mut type_aliases = Vec::new();
        let mut constants = Vec::new();
        let mut statics = Vec::new();
        let mut imports = Vec::new();
        let mut exports = Vec::new();

        for entity in entities {
            match entity {
                Entity::Module(e) => modules.push(e),
                Entity::Function(e) => functions.push(e),
                Entity::Struct(e) => structs.push(e),
                Entity::Enum(e) => enums.push(e),
                Entity::Trait(e) => traits.push(e),
                Entity::ImplBlock(e) => impl_blocks.push(e),
                Entity::TypeAlias(e) => type_aliases.push(e),
                Entity::Constant(e) => constants.push(e),
                Entity::Static(e) => statics.push(e),
                Entity::Import(e) => imports.push(e),
                Entity::Export(e) => exports.push(e),
            }
        }

        let sort_by_id = |a: &EntityId, b: &EntityId| a.cmp(b);

        modules.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        functions.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        structs.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        enums.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        traits.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        impl_blocks.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        type_aliases.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        constants.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        statics.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        imports.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        exports.sort_by(|a, b| sort_by_id(a.id(), b.id()));

        Self {
            modules,
            functions,
            structs,
            enums,
            traits,
            impl_blocks,
            type_aliases,
            constants,
            statics,
            imports,
            exports,
            diagnostics,
        }
    }

    /// Create an empty `RepositoryFacts`.
    pub fn empty() -> Self {
        Self {
            modules: Vec::new(),
            functions: Vec::new(),
            structs: Vec::new(),
            enums: Vec::new(),
            traits: Vec::new(),
            impl_blocks: Vec::new(),
            type_aliases: Vec::new(),
            constants: Vec::new(),
            statics: Vec::new(),
            imports: Vec::new(),
            exports: Vec::new(),
            diagnostics: Vec::new(),
        }
    }

    // ------------------------------------------------------------------
    // Accessors
    // ------------------------------------------------------------------

    pub fn modules(&self) -> &[ModuleFact] {
        &self.modules
    }
    pub fn functions(&self) -> &[FunctionFact] {
        &self.functions
    }
    pub fn structs(&self) -> &[StructFact] {
        &self.structs
    }
    pub fn enums(&self) -> &[EnumFact] {
        &self.enums
    }
    pub fn traits(&self) -> &[TraitFact] {
        &self.traits
    }
    pub fn impl_blocks(&self) -> &[ImplBlockFact] {
        &self.impl_blocks
    }
    pub fn type_aliases(&self) -> &[TypeAliasFact] {
        &self.type_aliases
    }
    pub fn constants(&self) -> &[ConstantFact] {
        &self.constants
    }
    pub fn statics(&self) -> &[StaticFact] {
        &self.statics
    }
    pub fn imports(&self) -> &[ImportFact] {
        &self.imports
    }
    pub fn exports(&self) -> &[ExportFact] {
        &self.exports
    }
    pub fn diagnostics(&self) -> &[ExtractionDiagnostic] {
        &self.diagnostics
    }

    pub fn is_empty(&self) -> bool {
        self.modules.is_empty()
            && self.functions.is_empty()
            && self.structs.is_empty()
            && self.enums.is_empty()
            && self.traits.is_empty()
            && self.impl_blocks.is_empty()
            && self.type_aliases.is_empty()
            && self.constants.is_empty()
            && self.statics.is_empty()
            && self.imports.is_empty()
            && self.exports.is_empty()
    }

    /// Total count of all entities (excluding diagnostics).
    pub fn entity_count(&self) -> usize {
        self.modules.len()
            + self.functions.len()
            + self.structs.len()
            + self.enums.len()
            + self.traits.len()
            + self.impl_blocks.len()
            + self.type_aliases.len()
            + self.constants.len()
            + self.statics.len()
            + self.imports.len()
            + self.exports.len()
    }

    /// Merge another `RepositoryFacts` into this one.
    ///
    /// All entities are merged and re-sorted. Diagnostics are appended.
    pub fn merge(&mut self, other: Self) {
        self.modules.extend(other.modules);
        self.functions.extend(other.functions);
        self.structs.extend(other.structs);
        self.enums.extend(other.enums);
        self.traits.extend(other.traits);
        self.impl_blocks.extend(other.impl_blocks);
        self.type_aliases.extend(other.type_aliases);
        self.constants.extend(other.constants);
        self.statics.extend(other.statics);
        self.imports.extend(other.imports);
        self.exports.extend(other.exports);
        self.diagnostics.extend(other.diagnostics);

        let sort_by_id = |a: &EntityId, b: &EntityId| a.cmp(b);
        self.modules.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        self.functions.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        self.structs.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        self.enums.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        self.traits.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        self.impl_blocks.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        self.type_aliases.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        self.constants.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        self.statics.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        self.imports.sort_by(|a, b| sort_by_id(a.id(), b.id()));
        self.exports.sort_by(|a, b| sort_by_id(a.id(), b.id()));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_evidence(path: &str) -> Evidence {
        Evidence::new(
            PathBuf::from(path),
            "test_node",
            0..10,
            1,
            1,
            1,
            10,
            Language::Rust,
        )
    }

    #[test]
    fn entity_id_deterministic() {
        let path = Path::new("src/lib.rs");
        let id1 = EntityId::from_location(&Language::Rust, "function", path, "foo", 42);
        let id2 = EntityId::from_location(&Language::Rust, "function", path, "foo", 42);
        assert_eq!(id1, id2);
    }

    #[test]
    fn entity_id_differs_for_different_names() {
        let path = Path::new("src/lib.rs");
        let id1 = EntityId::from_location(&Language::Rust, "function", path, "foo", 42);
        let id2 = EntityId::from_location(&Language::Rust, "function", path, "bar", 42);
        assert_ne!(id1, id2);
    }

    #[test]
    fn repository_facts_empty() {
        let facts = RepositoryFacts::empty();
        assert!(facts.is_empty());
        assert_eq!(facts.entity_count(), 0);
    }

    #[test]
    fn repository_facts_partitions_entities() {
        let ev = sample_evidence("test.rs");
        let func = FunctionFact::new(
            EntityId::from_location(&Language::Rust, "function", Path::new("test.rs"), "foo", 0),
            "foo",
            Visibility::Public,
            None,
            Vec::new(),
            false,
            false,
            false,
            None,
            None,
            None,
            ev,
        );

        let entities = vec![Entity::Function(func)];
        let facts = RepositoryFacts::from_entities(entities, Vec::new());

        assert_eq!(facts.functions().len(), 1);
        assert_eq!(facts.functions()[0].name(), "foo");
        assert!(facts.modules().is_empty());
    }

    #[test]
    fn repository_facts_deterministic_ordering() {
        let ev1 = sample_evidence("test.rs");
        let ev2 = sample_evidence("test.rs");
        let ev3 = sample_evidence("test.rs");

        let f1 = FunctionFact::new(
            EntityId::from_location(&Language::Rust, "function", Path::new("test.rs"), "bbb", 0),
            "bbb",
            Visibility::Public,
            None,
            Vec::new(),
            false,
            false,
            false,
            None,
            None,
            None,
            ev1,
        );
        let f2 = FunctionFact::new(
            EntityId::from_location(&Language::Rust, "function", Path::new("test.rs"), "aaa", 0),
            "aaa",
            Visibility::Public,
            None,
            Vec::new(),
            false,
            false,
            false,
            None,
            None,
            None,
            ev2,
        );
        let f3 = FunctionFact::new(
            EntityId::from_location(&Language::Rust, "function", Path::new("test.rs"), "ccc", 0),
            "ccc",
            Visibility::Public,
            None,
            Vec::new(),
            false,
            false,
            false,
            None,
            None,
            None,
            ev3,
        );

        // Verify same input produces same order
        let facts1 = RepositoryFacts::from_entities(
            vec![
                Entity::Function(f1.clone()),
                Entity::Function(f2.clone()),
                Entity::Function(f3.clone()),
            ],
            Vec::new(),
        );
        let facts2 = RepositoryFacts::from_entities(
            vec![
                Entity::Function(f3),
                Entity::Function(f1),
                Entity::Function(f2),
            ],
            Vec::new(),
        );

        let names1: Vec<&str> = facts1.functions().iter().map(|f| f.name()).collect();
        let names2: Vec<&str> = facts2.functions().iter().map(|f| f.name()).collect();
        assert_eq!(
            names1, names2,
            "ordering must be deterministic regardless of input order"
        );
        assert_eq!(facts1.functions().len(), 3);
    }

    #[test]
    fn evidence_roundtrip() {
        let ev = Evidence::new(
            PathBuf::from("src/main.rs"),
            "function_item",
            42..100,
            3,
            5,
            7,
            20,
            Language::Rust,
        );
        assert_eq!(ev.source_file(), Path::new("src/main.rs"));
        assert_eq!(ev.node_kind(), "function_item");
        assert_eq!(*ev.byte_range(), 42..100);
        assert_eq!(ev.start_line(), 3);
        assert_eq!(ev.start_column(), 5);
        assert_eq!(ev.end_line(), 7);
        assert_eq!(ev.end_column(), 20);
        assert_eq!(ev.language(), &Language::Rust);
    }

    #[test]
    fn merge_facts() {
        let ev = sample_evidence("a.rs");
        let f1 = FunctionFact::new(
            EntityId::from_location(&Language::Rust, "function", Path::new("a.rs"), "a", 0),
            "a",
            Visibility::Public,
            None,
            Vec::new(),
            false,
            false,
            false,
            None,
            None,
            None,
            ev,
        );
        let ev2 = sample_evidence("b.rs");
        let f2 = FunctionFact::new(
            EntityId::from_location(&Language::Rust, "function", Path::new("b.rs"), "b", 0),
            "b",
            Visibility::Public,
            None,
            Vec::new(),
            false,
            false,
            false,
            None,
            None,
            None,
            ev2,
        );

        let mut facts1 = RepositoryFacts::from_entities(vec![Entity::Function(f1)], Vec::new());
        let facts2 = RepositoryFacts::from_entities(vec![Entity::Function(f2)], Vec::new());
        facts1.merge(facts2);

        assert_eq!(facts1.functions().len(), 2);
    }

    #[test]
    fn entity_id_display() {
        let id = EntityId(0xdeadbeef);
        assert_eq!(format!("{id}"), "00000000deadbeef");
    }
}
