[package]
name = "kode-app"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
name = "kode_app"

[dependencies]
kode-acquisition = { path = "../../crates/acquisition" }
kode-analysis = { path = "../../crates/analysis" }
kode-common = { path = "../../crates/common" }
kode-graph = { path = "../../crates/graph" }
kode-storage = { path = "../../crates/storage" }
tracing = { workspace = true }
