[package]
name = "kode-graph"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
kode-acquisition = { path = "../acquisition" }
kode-analysis = { path = "../analysis" }
kode-common = { path = "../common" }
thiserror.workspace = true
